services:
  - type: web
    name: baby-cry-analysis
    env: python
    buildCommand: "pip install pipenv && pipenv install"
    startCommand: "pipenv run python run.py"
    region: oregon
    plan: free
